# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/sonnet': '@latest-kf6'
    'frameworks/syntax-highlighting': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'

- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'libraries/ktexttemplate': '@stable'
