# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kiconthemes': '@latest'
    'frameworks/kio': '@latest'
    'frameworks/sonnet': '@latest'
    'frameworks/syntax-highlighting': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kxmlgui': '@latest'
    'frameworks/ktextwidgets': '@latest'
    'frameworks/kcodecs': '@latest'
    'libraries/ktextaddons': '@stable'

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'third-party/grantlee' : '@stable'
