version = 1
SPDX-PackageName = "kpimtextedit"
SPDX-PackageSupplier = "Montel Laurent <montel@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/pim/kpimtextedit"

[[annotations]]
path = ["src/grantleebuilder/autotests/data/object-fill.svg", "src/grantleebuilder/autotests/sourcehtml", "src/emoticon/data/emoji.json", ".gitattributes", "readme-build-ftime.txt", "REUSE.toml", ".gersemirc", "src/kpimtextedit-index.qdoc", "src/kpimtextedit.qdoc", "src/kpimtextedit.qdocconf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["README-pre-commit.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023-2026 Laurent Montel <montel@kde.org>"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["CMakePresets.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 Laurent Montel <montel@kde.org>"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["README-qdoc.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023-2026 Laurent Montel <montel@kde.org>"
SPDX-License-Identifier = "BSD-3-Clause"
